-- ==========================================================
-- PROGRAMA DE BECAS EDUCATIVAS
-- Grupo: 03 - Fundación Educa Perú
-- ==========================================================

-- =============================
-- SECUENCIAS
-- =============================
CREATE SEQUENCE EDU_SEQ_ESTUDIANTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_INSTITUCION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_POSTULACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_BECA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_DONANTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_FINANCIAMIENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_SEGUIMIENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_PAGO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EDU_SEQ_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================
-- TABLAS PRINCIPALES
-- =============================

-- INSTITUCIÓN EDUCATIVA
CREATE TABLE EDU_INSTITUCION (
    ID_INSTITUCION NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    TIPO VARCHAR2(50),
    DIRECCION VARCHAR2(150),
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(100)
);

-- ESTUDIANTE
CREATE TABLE EDU_ESTUDIANTE (
    ID_ESTUDIANTE NUMBER PRIMARY KEY,
    DNI VARCHAR2(12) UNIQUE NOT NULL,
    NOMBRES VARCHAR2(80) NOT NULL,
    APELLIDOS VARCHAR2(80) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    GENERO CHAR(1),
    TELEFONO VARCHAR2(15),
    EMAIL VARCHAR2(100),
    DIRECCION VARCHAR2(150),
    ID_INSTITUCION NUMBER NOT NULL,
    PROMEDIO_ACTUAL NUMBER(4,2),
    CONDICION_SOCIOECONOMICA VARCHAR2(50),
    DISCAPACIDAD VARCHAR2(50),
    CONSTRAINT FK_EST_INST FOREIGN KEY (ID_INSTITUCION)
        REFERENCES EDU_INSTITUCION(ID_INSTITUCION)
);

CREATE INDEX IDX_EST_DNI ON EDU_ESTUDIANTE(DNI);

-- POSTULACIÓN
CREATE TABLE EDU_POSTULACION (
    ID_POSTULACION NUMBER PRIMARY KEY,
    ID_ESTUDIANTE NUMBER NOT NULL,
    FECHA_POSTULACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(30) CHECK (ESTADO IN ('PENDIENTE','APROBADA','RECHAZADA')),
    DOCUMENTOS_COMPLETOS CHAR(1) CHECK (DOCUMENTOS_COMPLETOS IN ('S','N')),
    OBSERVACION VARCHAR2(200),
    CONSTRAINT FK_POST_EST FOREIGN KEY (ID_ESTUDIANTE)
        REFERENCES EDU_ESTUDIANTE(ID_ESTUDIANTE)
);

CREATE INDEX IDX_POST_EST ON EDU_POSTULACION(ID_ESTUDIANTE);

-- PROGRAMA DE BECA
CREATE TABLE EDU_BECA (
    ID_BECA NUMBER PRIMARY KEY,
    NOMBRE_PROGRAMA VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    MONTO_TOTAL NUMBER(10,2),
    DURACION_MESES NUMBER,
    REQUISITOS VARCHAR2(200)
);

-- DONANTE
CREATE TABLE EDU_DONANTE (
    ID_DONANTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    TIPO VARCHAR2(50),
    CONTACTO VARCHAR2(100),
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

-- FINANCIAMIENTO
CREATE TABLE EDU_FINANCIAMIENTO (
    ID_FINANCIAMIENTO NUMBER PRIMARY KEY,
    ID_DONANTE NUMBER NOT NULL,
    ID_BECA NUMBER NOT NULL,
    MONTO_ASIGNADO NUMBER(10,2) NOT NULL,
    FECHA_APORTE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_FIN_DON FOREIGN KEY (ID_DONANTE)
        REFERENCES EDU_DONANTE(ID_DONANTE),
    CONSTRAINT FK_FIN_BEC FOREIGN KEY (ID_BECA)
        REFERENCES EDU_BECA(ID_BECA)
);

-- SEGUIMIENTO ACADÉMICO
CREATE TABLE EDU_SEGUIMIENTO (
    ID_SEGUIMIENTO NUMBER PRIMARY KEY,
    ID_ESTUDIANTE NUMBER NOT NULL,
    PERIODO VARCHAR2(10),
    PROMEDIO NUMBER(4,2),
    ESTADO_ACADEMICO VARCHAR2(30),
    OBSERVACIONES VARCHAR2(200),
    CONSTRAINT FK_SEG_EST FOREIGN KEY (ID_ESTUDIANTE)
        REFERENCES EDU_ESTUDIANTE(ID_ESTUDIANTE)
);

-- PAGO / DESEMBOLSO
CREATE TABLE EDU_PAGO (
    ID_PAGO NUMBER PRIMARY KEY,
    ID_BECA NUMBER NOT NULL,
    ID_ESTUDIANTE NUMBER NOT NULL,
    MONTO NUMBER(10,2),
    FECHA_PAGO DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20),
    CONSTRAINT FK_PAG_BEC FOREIGN KEY (ID_BECA)
        REFERENCES EDU_BECA(ID_BECA),
    CONSTRAINT FK_PAG_EST FOREIGN KEY (ID_ESTUDIANTE)
        REFERENCES EDU_ESTUDIANTE(ID_ESTUDIANTE)
);

-- AUDITORÍA
CREATE TABLE EDU_AUDITORIA (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    ENTIDAD VARCHAR2(50),
    OPERACION VARCHAR2(20),
    FECHA DATE DEFAULT SYSDATE,
    USUARIO VARCHAR2(50),
    DETALLE VARCHAR2(200)
);

-- =============================
-- REGLAS Y CONSTRAINTS ADICIONALES
-- =============================
ALTER TABLE EDU_ESTUDIANTE ADD CONSTRAINT CHK_EST_GENERO CHECK (GENERO IN ('M','F'));
ALTER TABLE EDU_PAGO ADD CONSTRAINT CHK_PAG_ESTADO CHECK (ESTADO IN ('PENDIENTE','REALIZADO','ANULADO'));

-- =============================
-- TRIGGERS PARA AUTONUMERACIÓN
-- =============================
CREATE OR REPLACE TRIGGER TRG_ESTUDIANTE_BI
BEFORE INSERT ON EDU_ESTUDIANTE
FOR EACH ROW
BEGIN
  :NEW.ID_ESTUDIANTE := EDU_SEQ_ESTUDIANTE.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_POSTULACION_BI
BEFORE INSERT ON EDU_POSTULACION
FOR EACH ROW
BEGIN
  :NEW.ID_POSTULACION := EDU_SEQ_POSTULACION.NEXTVAL;
END;
/
